name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.0

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test ./...

      # Run go format
      - name: Run go format
        run: go fmt ./...

      # Run go lint
      - name: Run go lint
        run: go lint ./...

      # Run sqlc generate
      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: "1.30.0"
      - run: sqlc diff
